version: '3'
services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
    restart: always
    labels:
      - "traefik.frontend.rule=Host:html.bf0.ch" # traefik will request SSL from letsencrypt
      - "traefik.port=80" # enable this port in so traefik can proxy it
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.backend=classroom-html-monitor"
    networks:
      - web
      - default
  db:
    image: postgres:9.6
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
volumes:
   db-data:
     driver: local
networks:
  web:
    external: true